const fs = require('fs-extra');
const concat = require('concat');

(async function build() {
    const files = [
        './dist/apps/embed/runtime.js',
        './dist/apps/embed/polyfills.js',
        // './dist/apps/embed/scripts.js', Not currently being generated by ng build.
        './dist/apps/embed/main.js'
    ];

    await fs.ensureDir('site')
    await concat(files, 'site/embed.js')
    await fs.copyFile('./dist/apps/embed/styles.css', 'site/styles.css')

    // If we need pictures or other assets, uncomment below.
    // await fs.copy('./dist/apps/embed/assets/', 'site/assets/')
})()
